apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}-prod
spec:
  destination:
    namespace: {{ .Values.application.environments.prod }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/prod
    repoURL: https://{{ .Values.pipeline.gitea.host }}/gitea/{{ .Values.pipeline.webhook.github.repo }}-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true