kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-build-workspace
  namespace: {{ .Values.application.environments.cicd }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client    
  volumeMode: Filesystem
